import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`p-6 ${inter.className}`}>
        <nav className='pb-2'>
          <ul className='flex gap-4'>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/about">About</Link></li>
            <li><Link href="/posts">posts</Link></li>
            <li className='relative group'><Link href="/blog">Blog</Link>
              <ul className='absolute hidden group-hover:block bg-white p-4 shadow'>
                <li><Link href="/blog/blog1">Blog</Link></li>
              </ul>
            </li>
          </ul>
        </nav>
        <hr className='mb-10' />
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  )
}
